mnemonic1: bless harvest huge empower join laundry toddler cheap glass crop deny anxiety
mnemonic2: tenant weather comfort fun seminar lucky salt city palm below clever fuel renew gap melt glove attack zone brand food rain friend plunge vessel
password: Test@123!
