account1:
  mnemonic: bless harvest huge empower join laundry toddler cheap glass crop deny anxiety
  address: aura1jpql4539yz0gmu6wqfd7eqaw5wwpd3g2mcxu4k
account2:
  mnemonic: tenant weather comfort fun seminar lucky salt city palm below clever fuel renew gap melt glove attack zone brand food rain friend plunge vessel
  address: aura1jm3x0e2s9fekwvvfpyn9h75lx0ffwjjhct8mqt
account3:
  mnemonic: invest ill trim close average clog employ caution glass jazz middle swap record little cherry girl weird gate aim master time method balance famous
  address: aura10dyct5559d7c767mkmjmzh022fq52ara95vdje
password: Test@123!
