name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  local-test:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-chrome
        options: --health-cmd '/opt/bin/check-grid.sh'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml

      - name: Run local tests
        run: mvn -B test -Pweb-execution -Dsuite=local -Dtarget=local -Dheadless=true -Dbrowser=chrome

# disabled job to show it as a reference since the browserstack sdk dynamically loads classes and generates conflicts
# with the current libraries
  browserstack-test:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          project-name: selenium-lean-java-architecture

      - name: Start BrowserStackLocal Tunnel
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start

      - name: Run browserstack tests
        run: mvn -B test -Pbrowserstack

      - name: Start BrowserStackLocal Tunnel
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop